const ActionType = {

    IS_LOADING: "IS_LOADING",
    LOADING_MSG: "LOADING_MSG",
    USER_TOKEN: "USER_TOKEN",
    DEVICE_TOKEN_REDUCER: "DEVICE_TOKEN_REDUCER",
    SCREEN_STATE_REDUCER: "SCREEN_STATE_REDUCER",

  
  
    //Redux actions
    USER_DATA: "USER_DATA",
    IS_LOGIN: "IS_LOGIN",
    INTERNET_CONNECTED: "INTERNET_CONNECTED",
    INTERNET_DISCONNECTED: "INTERNET_DISCONNECTED",
    DASHBOARD_REDUCER:"DASHBOARD_REDUCER",
    WHAT_IF_CALCULATOR_REDUCER:"WHAT_IF_CALCULATOR_REDUCER",
    MESAGE_REDUCER:"MESAGE_REDUCER",
    CALL_PLAN_REDUCER:"CALL_PLAN_REDUCER",
    SETTING_REDUCER:"SETTING_REDUCER",
  
    //Auth Saga Actions
    DO_LOGIN_SAGA: "DO_LOGIN_SAGA",
    DO_LOGOUT_SAGA: "DO_LOGOUT_SAGA",
    CHANGE_PASSWORD_SAGA: "CHANGE_PASSWORD_SAGA",
    TOKEN_EXPIRED_SAGA: "TOKEN_EXPIRED_SAGA",
    DO_REGISTRATION_SAGA: "DO_REGISTRATION_SAGA",
    DASHBOARD_SAGA:"DASHBOARD_SAGA",
    WHAT_IF_CALCULATOR_SAGA:"WHAT_IF_CALCULATOR_SAGA",
    MESAGE_SAGA:"MESAGE_SAGA",
    CALL_PLAN_SAGA:"CALL_PLAN_SAGA",
    SETTING_SAGA:"SETTING_SAGA",
    
  
  
  
  
  
  
  }
  
  export default ActionType